# escape=`
FROM microsoft/nanoserver:10.0.14393.1593

LABEL maintainer="Gregory Boddin" \
  org.label-schema.name="Drone Github Search Downstream" \
  org.label-schema.vendor="Gregory Boddin" \
  org.label-schema.schema-version="1.0"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ADD release\github-search-downstream.exe c:\github-search-downstream.exe
ENTRYPOINT [ "c:\\github-search-downstream.exe" ]